### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by mhubii**
~~This PR aims to re-think the purpose of this repository through the following considerations~~
- ~~Examples should live outside this repository~~
- ~~Moveit configuration should live outside this repository (since configuration can be very individual)~~

This PR adds
- Documentation
- Composable node

Therefore, following updates are necessary
- README
- `lbr_spinner` removal
- ~~Introduction of another repository to hold examples and moveit~~
- Readthedocs (https://github.com/KCL-BMEIS/lbr_fri_ros2_stack_doc)
- ~~Consider removing "stack" from the name~~
- Update doc in https://github.com/kCL-BMEIS/fri
- Move `examples` to `demos`
- Fixes friction bug in `URDF`

### CODE REVIEW

**Comment by cmower** [comment]
I would also consider
* Create an organization. There are several repos, and you could either fork the repos from KCL-BMEIS or transfer ownership. Otherwise, the code base feels quite scattered.
* I wouldn't recommend having a separate repo for the documentation. You can setup a github action that automatically builds and pushes the website to a branch called `gh-pages` and then in settings you can tell github to host the site via github pages for this branch. See https://github.com/cmower/aruco_markers as an example.
* I mostly agree with putting more advanced examples in a dedicated repo (e.g. admittance control). However, I would keep at least 1 or 2 simple "hello, world!" type examples. This is just so people can run something very simple right after building. They may not want to install all the examples immediately and would be good to keep something simple. Also, something simple like a figure-of-eight end-effector trajectory is a nice illustration for them to see basic implementation. I suggest one python and one c++ example.
* Also, consider removing `ros2` from the name or maybe use `ros`. I know we don't plan to continue supporting ros 1, but what if ros3 comes along one day? But either way, `ros` or without is cleaner in my opinion. 
* Also, there are links in the readme that link to King's internal sites. This will be frustrating for those outside King's.  We should move these links to somewhere internal to us and replace with links to documentation that is public - or not at all (people with Kuka robots should have access to this themselves).

**Comment by mhubii** [comment]
all very nice suggestions, thanks @cmower . Let's move this repository to https://github.com/ros-lbr eventually

let's also keep the examples for now and re-name them demos. Got to double check with the documentation though, maybe won't do a `gh-pages` branch, as most other ros projects don't do that, although it sounds convenient!

**Comment by cmower** [comment]
Re gh-pages, that's just one way of doing it and I have a standard workflow template I use, so I don't need to change it. Probably read-the-docs is more standard for ROS and something else for the workflow

**Comment by mhubii** [comment]
The documentation will be built on `doxysphinx`, leaving an example for reference https://github.com/mhubii/doxysphinx_demo/

**Review by mhubii — COMMENTED** [review]
legit

**Pull request merged**
